//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyMe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeautyMeDBContext : DbContext
    {
        public BeautyMeDBContext()
            : base("name=BeautyMeDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<Business> Business { get; set; }
        public virtual DbSet<Business_can_give_treatment> Business_can_give_treatment { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Future_Appointment> Future_Appointment { get; set; }
        public virtual DbSet<Professional> Professional { get; set; }
        public virtual DbSet<Review_Business> Review_Business { get; set; }
        public virtual DbSet<Treatment_for_appointment> Treatment_for_appointment { get; set; }
        public virtual DbSet<Type_Treatment> Type_Treatment { get; set; }
    }
}
